# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

# scheduling
schedules:
  - cron: "0 0 * * *"
    displayName: Daily Build
    branches:
      include: ["master"]
    always: "false" # Don't run unless changes happen

# build steps
steps:

# checkout source code
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  clean: true  # if true, execute `execute git clean -ffdx && git reset --hard HEAD` before fetching
  #fetchDepth: number  # the depth of commits to ask Git to fetch; defaults to no limit
  #lfs: boolean  # whether to download Git-LFS files; defaults to false
  # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules; defaults to not checking out submodules
  submodules: recursive
  # path: string  # path to check out source code, relative to the agent's build directory (e.g. \_work\1); defaults to a directory called `s`
  #persistCredentials: boolean  # if 'true', leave the OAuth token in the Git config after the initial fetch; defaults to false

# run vpc first
- task: CmdLine@2
  displayName: Create solution using VPC
  inputs:
    workingDirectory: '$(Build.Repository.LocalPath)'
    script: '
    cd src\
    
    devtools\bin\vpc.exe /hl2 /hl2mp /episodic /hl2r +everything /define:VS2019 /mksln everything.sln
    '

# run msbuild on the solution
- task: MSBuild@1
  displayName: Build solution using Visual Studio 2019
  inputs:
    solution: '**/*.sln'
    configuration: 'Release'
    maximumCpuCount: true

# copy files from $(BuildConfiguration) folders
# some files may not be copied
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.Repository.LocalPath)'
    contents: '**/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)'

# publish artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop